spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mart?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: "Karthik123#"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
